import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function validateNPI(npi: string): boolean {
  return /^\d{10}$/.test(npi);
}

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(amount);
}

export function formatUSDate(dateStr: string): string {
  if (!dateStr || !dateStr.includes('-')) return dateStr;
  const [year, month, day] = dateStr.split('-');
  return `${month}/${day}/${year}`;
}

export const CARC_SUGGESTIONS: Record<string, { groupCode: 'CO' | 'PR' | 'OA' | 'PI' | 'CR', carc: string, rarc?: string }> = {
  // COB & Other Insurance
  'cob': { groupCode: 'CO', carc: '22', rarc: 'N24' },
  'coordination of benefits': { groupCode: 'CO', carc: '22', rarc: 'N24' },
  'primary payer': { groupCode: 'CO', carc: '22' },
  'missing eob': { groupCode: 'CO', carc: '236' },
  'other insurance': { groupCode: 'CO', carc: '22' },
  
  // Patient Responsibility
  'deductible': { groupCode: 'PR', carc: '1' },
  'coinsurance': { groupCode: 'PR', carc: '2' },
  'copay': { groupCode: 'PR', carc: '3' },
  'patient responsibility': { groupCode: 'PR', carc: '3' },

  // Contractual & Bundling
  'contractual': { groupCode: 'CO', carc: '45' },
  'fee schedule': { groupCode: 'CO', carc: '45' },
  'maximum allowance': { groupCode: 'CO', carc: '45' },
  'bundle': { groupCode: 'CO', carc: '97', rarc: 'M15' },
  'inclusive': { groupCode: 'CO', carc: '97', rarc: 'M15' },
  'mutually exclusive': { groupCode: 'CO', carc: '97' },
  'unbundled': { groupCode: 'CO', carc: '97' },

  // Coverage & Medical Necessity
  'not covered': { groupCode: 'CO', carc: '96' },
  'non-covered': { groupCode: 'CO', carc: '96' },
  'medical necessity': { groupCode: 'CO', carc: '50', rarc: 'M115' },
  'experimental': { groupCode: 'CO', carc: '55' },
  'investigational': { groupCode: 'CO', carc: '55' },
  'routine': { groupCode: 'CO', carc: '119' },
  'preventive': { groupCode: 'CO', carc: '119' },

  // Authorization & Precertification
  'prior authorization': { groupCode: 'CO', carc: '197' },
  'precertification': { groupCode: 'CO', carc: '197' },
  'authorization absent': { groupCode: 'CO', carc: '197' },
  'authorization exceeded': { groupCode: 'CO', carc: '198' },
  'referral absent': { groupCode: 'CO', carc: '8' },
  'referral missing': { groupCode: 'CO', carc: '8' },

  // Timely Filing
  'timely filing': { groupCode: 'CO', carc: '29' },
  'time limit': { groupCode: 'CO', carc: '29' },
  'filing limit': { groupCode: 'CO', carc: '29' },

  // Eligibility & Enrollment
  'terminated': { groupCode: 'PR', carc: '27' },
  'not eligible': { groupCode: 'PR', carc: '27' },
  'coverage expired': { groupCode: 'PR', carc: '27' },
  'inactive': { groupCode: 'PR', carc: '27' },
  'not enrolled': { groupCode: 'PR', carc: '26' },
  'coverage not in effect': { groupCode: 'PR', carc: '26' },

  // Duplicates
  'duplicate': { groupCode: 'CO', carc: '18' },
  'duplicate claim': { groupCode: 'CO', carc: '18' },
  'previously processed': { groupCode: 'CO', carc: '18' },
  'already paid': { groupCode: 'CO', carc: '18' },

  // Coding & Documentation
  'modifier missing': { groupCode: 'CO', carc: '4' },
  'invalid modifier': { groupCode: 'CO', carc: '4' },
  'inconsistent modifier': { groupCode: 'CO', carc: '4' },
  'diagnosis inconsistent': { groupCode: 'CO', carc: '11' },
  'procedure inconsistent': { groupCode: 'CO', carc: '11' },
  'documentation required': { groupCode: 'CO', carc: '16', rarc: 'M127' },
  'missing documentation': { groupCode: 'CO', carc: '16', rarc: 'M127' },
  'medical records': { groupCode: 'CO', carc: '16', rarc: 'M127' },
  'invalid code': { groupCode: 'CO', carc: '16' },
  'missing code': { groupCode: 'CO', carc: '16' },
  'ndc missing': { groupCode: 'CO', carc: '16', rarc: 'M119' },
  'invalid ndc': { groupCode: 'CO', carc: '16', rarc: 'M119' },

  // Provider Issues
  'provider not eligible': { groupCode: 'CO', carc: 'B7' },
  'out of network': { groupCode: 'PR', carc: '242' },
  'non-participating': { groupCode: 'PR', carc: '242' },
  'taxonomy missing': { groupCode: 'CO', carc: '16', rarc: 'N290' },
  'npi missing': { groupCode: 'CO', carc: '16', rarc: 'N257' },
};

export function getSuggestedCodes(reason: string) {
  const normalized = reason.toLowerCase();
  for (const [key, value] of Object.entries(CARC_SUGGESTIONS)) {
    if (normalized.includes(key)) return value;
  }
  return { groupCode: 'OA' as const, carc: '96' }; // Default
}

export const CARC_DESCRIPTIONS: Record<string, string> = {
  '1': 'Deductible Amount',
  '2': 'Coinsurance Amount',
  '3': 'Copayment Amount',
  '4': 'The procedure code is inconsistent with the modifier used or a required modifier is missing.',
  '5': 'The procedure code/bill type is inconsistent with the place of service.',
  '6': 'The procedure/revenue code is inconsistent with the patient\'s age.',
  '7': 'The procedure/revenue code is inconsistent with the patient\'s gender.',
  '8': 'The procedure code is inconsistent with the provider type/specialty (taxonomy).',
  '9': 'The diagnosis is inconsistent with the patient\'s age.',
  '10': 'The diagnosis is inconsistent with the patient\'s gender.',
  '11': 'The diagnosis is inconsistent with the procedure.',
  '12': 'The diagnosis is inconsistent with the provider type.',
  '13': 'The date of service is not within a period of skilled nursing facility stay.',
  '14': 'The date of service is not within a period of hospice care.',
  '15': 'The procedure code is inconsistent with the qualifier.',
  '16': 'Claim/service lacks information or has submission/billing error(s) which is needed for adjudication.',
  '18': 'Exact duplicate claim/service',
  '19': 'This is a work-related injury/illness and thus the liability of the Worker\'s Compensation Carrier.',
  '20': 'This injury/illness is covered by the liability carrier.',
  '21': 'This injury/illness is covered by the no-fault carrier.',
  '22': 'This care may be covered by another payer per coordination of benefits',
  '23': 'The impact of prior payer(s) adjudication including payments and/or adjustments.',
  '24': 'Charges are covered under a different plan/program.',
  '26': 'Expenses incurred prior to coverage.',
  '27': 'Expenses incurred after coverage terminated.',
  '29': 'The time limit for filing has expired.',
  '31': 'Patient cannot be identified as our insured.',
  '35': 'Lifetime benefit maximum has been reached.',
  '39': 'Services denied at the time authorization/pre-certification was requested.',
  '40': 'Charges do not meet qualifications for emergent/urgent care.',
  '45': 'Charge exceeds fee schedule/maximum allowable or contracted/legislated fee arrangement',
  '49': 'This is a non-covered service because it is a routine exam or screening procedure done in conjunction with a routine exam.',
  '50': 'These are non-covered services because this is not deemed a "medical necessity" by the payer',
  '51': 'These are non-covered services because this is a pre-existing condition.',
  '54': 'Multiple physicians/assistants are not covered in this case.',
  '55': 'Procedure/treatment is deemed experimental/investigational by the payer.',
  '56': 'Procedure/treatment has not been deemed "proven to be effective" by the payer.',
  '58': 'Treatment was deemed by the payer to have been rendered in an inappropriate or invalid place of service.',
  '59': 'Processed based on multiple diagnostic imaging (MDI) reduction logic.',
  '61': 'Penalty for failure to obtain second surgical opinion.',
  '66': 'Blood Deductible.',
  '69': 'Day limit exceeded.',
  '70': 'Cost of care exceeds maximum.',
  '74': 'This service/excise tax is not covered.',
  '75': 'Feature/attribute of service is not covered or is bundled.',
  '76': 'Discontinued administrative code.',
  '85': 'Patient is not a covered family member.',
  '89': 'Professional fees for radiology services not covered.',
  '90': 'Ingredient cost adjustment.',
  '91': 'Dispensing fee adjustment.',
  '94': 'Processed in Excess of charges.',
  '95': 'Plan procedures not followed.',
  '96': 'Non-covered charge(s)',
  '97': 'The benefit for this service is included in the payment/allowance for another service/procedure that has already been adjudicated.',
  '100': 'Payment made to patient/insured/responsible party/employer.',
  '101': 'Predetermination: anticipated payment upon completion of services or claim adjudication.',
  '107': 'Related or qualifying claim has not been received.',
  '108': 'Rent/purchase guidelines not met.',
  '109': 'Claim not covered by this payer/processor.',
  '110': 'Billing date precedes date of service.',
  '114': 'Procedure/product not on formulary.',
  '115': 'Procedure postponed, canceled, or delayed.',
  '117': 'Transportation is only covered to the nearest facility.',
  '118': 'ESRD network support adjustment.',
  '119': 'Benefit maximum for this time period or occurrence has been reached',
  '121': 'Indemnification adjustment - error in payment.',
  '122': 'Psychiatric reduction.',
  '125': 'Submission/billing error(s).',
  '128': 'New-born\'s services are covered in the mother\'s allowance.',
  '129': 'Prior processing information appears incorrect.',
  '130': 'Claim submission fee.',
  '131': 'Claim specific negotiated discount.',
  '132': 'Prearranged demonstration project adjustment.',
  '133': 'The disposition of the claim/service is pending further review.',
  '134': 'Technical component only.',
  '135': 'Interim payment.',
  '136': 'Failure to follow prior payer\'s coverage rules.',
  '137': 'Regulatory Surcharges, Assessments, etc.',
  '138': 'Appeal procedures not followed or time limits not met.',
  '139': 'Contracted funding agreement - Subscriber is employed by the provider.',
  '140': 'Patient/Insured health identification number and name do not match.',
  '142': 'Monthly Medicaid patient liability amount.',
  '143': 'Portability provisions not met.',
  '144': 'Incentive adjustment, e.g. preferred product/service.',
  '146': 'Diagnosis was invalid for the date(s) of service reported.',
  '147': 'Provider contracted/negotiated rate expired or not on file.',
  '148': 'Information from another provider was not provided or was insufficient/incomplete.',
  '149': 'Lifetime benefit maximum has been reached for this service/benefit category.',
  '150': 'Payer deems the information submitted does not support this level of service.',
  '151': 'Payment adjusted because the payer deems the information submitted does not support this many/frequency of services.',
  '152': 'Payer deems the information submitted does not support this length of service.',
  '153': 'Payer deems the information submitted does not support this dosage.',
  '154': 'Payer deems the information submitted does not support this day\'s supply.',
  '155': 'Patient refused the service/procedure.',
  '157': 'Service/procedure was provided as a result of an act of war.',
  '158': 'Service/procedure was provided outside of the United States.',
  '159': 'Service/procedure was provided as a result of terrorism.',
  '160': 'Injury/illness was the result of an activity that is a programmed exclusion.',
  '161': 'Provider was not certified/eligible to be paid for this service/procedure on this date of service.',
  '162': 'State-mandated Requirement for Provider to accept Medicaid assignment.',
  '163': 'Attachment Referenced on the Claim was not Received.',
  '164': 'Attachment Referenced on the Claim was Not Required.',
  '165': 'Claim spans eligible and ineligible periods of coverage.',
  '166': 'These services were submitted after this payer\'s responsibility ended.',
  '167': 'This (these) service(s) is (are) not covered.',
  '168': 'Service was provided by a certified medical assistant.',
  '169': 'Alternate benefit has been provided.',
  '170': 'Payment is denied when performed/billed by this type of provider.',
  '171': 'Payment is denied when performed/billed by this type of provider in this type of facility.',
  '172': 'Payment is adjusted when performed/billed by a provider of this specialty.',
  '173': 'Service/equipment was not prescribed by a physician.',
  '174': 'Service was not prescribed prior to delivery.',
  '175': 'Prescription is not on file.',
  '176': 'Prescription is outdated.',
  '177': 'Patient has not met the required eligibility requirements.',
  '178': 'Patient has not met the required residency requirements.',
  '179': 'Patient has not met the required spend down requirements.',
  '180': 'Patient has not met the required waiting period requirements.',
  '181': 'Procedure code was invalid on the date of service.',
  '182': 'Procedure modifier was invalid on the date of service.',
  '183': 'The referring provider is not eligible to refer the service billed.',
  '184': 'The certifying provider is not eligible to certify the service billed.',
  '185': 'The rendering provider is not eligible to perform the service billed.',
  '186': 'Level of care change adjustment.',
  '187': 'Consumer Spending Account offset.',
  '188': 'This product/service is denied or reduced in accordance with the Payer\'s coverage policy.',
  '189': '"Not otherwise classified" or "Unlisted" procedure code (CPT/HCPCS) was billed when there is a specific procedure code available.',
  '190': 'Original payment decision is being maintained. Upon review, it was determined that this claim was processed originally at the correct level.',
  '191': 'This is a refund of a previous overpayment.',
  '192': 'Non-standard adjustment code from paper remittance.',
  '193': 'Original payment decision is being maintained. Upon review, it was determined that this claim was processed originally at the correct level.',
  '194': 'Anesthesia performed by the operating surgeon is not a covered benefit.',
  '195': 'Refund of an actual overpayment.',
  '197': 'Precertification/authorization/notification absent.',
  '198': 'Precertification/authorization/notification exceeded.',
  '199': 'Revenue code and Service code are inconsistent.',
  '200': 'Provider performance program incentive payment.',
  '201': 'Workers Compensation case settled.',
  '202': 'Non-covered personal comfort or convenience items.',
  '203': 'Discontinued or reduced service.',
  '204': 'This service/equipment cannot be billed separately.',
  '205': 'Pharmacy discount card processing fee.',
  '206': 'National Provider Identifier (NPI) missing.',
  '207': 'National Provider Identifier (NPI) invalid format.',
  '208': 'National Provider Identifier (NPI) not on file.',
  '209': 'Per day limit reached.',
  '210': 'Payment adjusted because the payer deems the information submitted does not support this level of service.',
  '211': 'National Drug Code (NDC) not on file.',
  '212': 'Administrative surcharges are not covered.',
  '213': 'Non-compliance with the physician query.',
  '215': 'Based on subrogation of a third party liability claim, which was likely the result of an accident.',
  '216': 'Based on the findings of a review organization.',
  '219': 'Based on extent of injury.',
  '222': 'Exceeds the contracted maximum number of hours/days/units by this provider for this period.',
  '223': 'Adjustment based on the destination of the transfer.',
  '224': 'Patient identification compromised.',
  '225': 'Penalty or Interest Adjustment.',
  '226': 'Information requested from the Billing/Rendering Provider was not provided or was insufficient/incomplete.',
  '227': 'Information requested from the Patient/Insured was not provided or was insufficient/incomplete.',
  '228': 'Information requested from the Referring/Ordering Provider was not provided or was insufficient/incomplete.',
  '229': 'Administrative fees.',
  '231': 'Mutually exclusive procedures cannot be done on the same day/setting.',
  '232': 'This care may be covered by another payer per coordination of benefits.',
  '233': 'Services/charges related to the treatment of a hospital-acquired condition or preventable medical error.',
  '234': 'This procedure is not paid separately.',
  '235': 'Sales Tax.',
  '236': 'This procedure or procedure/modifier combination is not compatible with another procedure or procedure/modifier combination provided on the same day according to the National Correct Coding Initiative or common billing conventions',
  '237': 'Legislated/Contracted requirement not met.',
  '238': 'Claim spans eligible and ineligible periods of coverage.',
  '239': 'Claim spans eligible and ineligible periods of coverage.',
  '240': 'The diagnosis is inconsistent with the procedure.',
  '241': 'Number of days/units exceeds the maximum allowed.',
  '242': 'Services not provided by network/primary care providers.',
  '243': 'Services not authorized by network/primary care providers.',
  '245': 'Provider performance program incentive payment.',
  '246': 'This non-payable code is for required reporting only.',
  '247': 'Deductible for Professional Services.',
  '248': 'Coinsurance for Professional Services.',
  '249': 'This claim has been identified as a readmission.',
  '250': 'The attachment/other documentation that was received was incorrect or incomplete.',
  '251': 'The attachment/other documentation that was received was incorrect or incomplete.',
  '252': 'An attachment/other documentation is required to adjudicate this claim/service.',
  '253': 'Sequestration - reduction in federal spending.',
  '254': 'Provincial sales tax.',
  '256': 'Original payment decision is being maintained. Upon review, it was determined that this claim was processed originally at the correct level.',
  '257': 'The disposition of the claim/service is pending further review.',
  '258': 'Claim/service denied because the related or qualifying claim/service was not also subsequently received.',
  '259': 'Additional payment for Transitional Care Management.',
  '260': 'Processed under Medicaid ACA enhanced physician payment provisions.',
  '261': 'The procedure code is inconsistent with the provider type/specialty (taxonomy).',
  '262': 'Adjustment for menses.',
  '263': 'Adjustment for pregnancy.',
  '264': 'Adjustment for smoking.',
  '265': 'Adjustment for weight.',
  '266': 'Adjustment for other.',
  '267': 'Claim/service lacks information or has submission/billing error(s) which is needed for adjudication.',
  '268': 'The procedure code is inconsistent with the modifier used or a required modifier is missing.',
  '269': 'The procedure code/bill type is inconsistent with the place of service.',
  '270': 'The procedure/revenue code is inconsistent with the patient\'s age.',
  '271': 'The procedure/revenue code is inconsistent with the patient\'s gender.',
  '272': 'The procedure code is inconsistent with the provider type/specialty (taxonomy).',
  '273': 'The diagnosis is inconsistent with the patient\'s age.',
  '274': 'The diagnosis is inconsistent with the patient\'s gender.',
  '275': 'The diagnosis is inconsistent with the procedure.',
  '276': 'The diagnosis is inconsistent with the provider type.',
  '277': 'The date of service is not within a period of skilled nursing facility stay.',
  '278': 'The date of service is not within a period of hospice care.',
  '279': 'The procedure code is inconsistent with the qualifier.',
  '280': 'Claim/service lacks information or has submission/billing error(s) which is needed for adjudication.',
  '281': 'Exact duplicate claim/service.',
  '282': 'This is a work-related injury/illness and thus the liability of the Worker\'s Compensation Carrier.',
  '283': 'This injury/illness is covered by the liability carrier.',
  '284': 'This injury/illness is covered by the no-fault carrier.',
  '285': 'This care may be covered by another payer per coordination of benefits.',
  '286': 'The impact of prior payer(s) adjudication including payments and/or adjustments.',
  '287': 'Charges are covered under a different plan/program.',
  '288': 'Expenses incurred prior to coverage.',
  '289': 'Expenses incurred after coverage terminated.',
  '290': 'The time limit for filing has expired.',
};

export const RARC_DESCRIPTIONS: Record<string, string> = {
  'N1': 'Alert: You may appeal this decision in writing.',
  'N2': 'Alert: You may not appeal this decision.',
  'N3': 'Alert: You may appeal this decision in writing.',
  'N4': 'Alert: You may not appeal this decision.',
  'N10': 'Alert: You may appeal this decision in writing.',
  'N20': 'Service not payable with other service(s).',
  'N24': 'Missing/incomplete/invalid Electronic Explanation of Benefits (EEOB) from the primary payer',
  'N30': 'Patient ineligible on this date of service.',
  'N31': 'Missing/incomplete/invalid other payer\'s explanation of benefits.',
  'N34': 'Incorrect claim form used.',
  'N40': 'Missing/incomplete/invalid patient\'s birth date.',
  'N54': 'Missing/incomplete/invalid physician/provider signature.',
  'N65': 'Missing/incomplete/invalid procedure code(s).',
  'N115': 'This decision was based on a local coverage determination (LCD).',
  'N122': 'This decision was based on a National Coverage Determination (NCD).',
  'N130': 'Alert: You may appeal this decision in writing.',
  'N211': 'Alert: You may not appeal this decision.',
  'N362': 'The number of days or units of service exceeds our acceptable maximum.',
  'N381': 'This service was not authorized by the primary care provider.',
  'N382': 'This service was not authorized by the network provider.',
  'N517': 'Resubmit a new claim with the requested information.',
  'N519': 'Invalid/missing provider/group NPI.',
  'N522': 'Missing/incomplete/invalid primary identifier.',
  'N569': 'Missing/incomplete/invalid other payer\'s remittance advice.',
  'N657': 'This should be billed to the payer.',
  'N706': 'Missing/incomplete/invalid billing provider name.',
  'N707': 'Missing/incomplete/invalid billing provider address.',
  'N708': 'Missing/incomplete/invalid billing provider city, state, zip.',
  'MA01': 'If you do not agree with this determination, you have the right to appeal',
  'MA13': 'Alert: You may appeal this decision in writing.',
  'MA15': 'Your claim has been separated to expedite processing.',
  'MA18': 'The claim was processed in accordance with Medicare instructions.',
  'MA19': 'Information was not provided or was insufficient/incomplete.',
  'MA30': 'Missing/incomplete/invalid patient\'s birth date.',
  'MA36': 'Missing/incomplete/invalid physician/provider signature.',
  'MA39': 'Missing/incomplete/invalid procedure code(s).',
  'MA44': 'Alert: You may appeal this decision in writing.',
  'MA48': 'Alert: You may appeal this decision in writing.',
  'MA50': 'Missing/incomplete/invalid patient\'s name.',
  'MA61': 'Missing/incomplete/invalid social security number.',
  'MA63': 'Missing/incomplete/invalid health insurance claim number.',
  'MA66': 'Missing/incomplete/invalid name of the insured.',
  'MA67': 'Missing/incomplete/invalid address of the insured.',
  'MA72': 'Missing/incomplete/invalid other payer\'s identifier.',
  'MA83': 'Missing/incomplete/invalid other payer\'s name.',
  'MA84': 'Missing/incomplete/invalid other payer\'s address.',
  'MA88': 'Missing/incomplete/invalid other payer\'s city, state, zip.',
  'MA89': 'Missing/incomplete/invalid other payer\'s policy number.',
  'MA90': 'Missing/incomplete/invalid other payer\'s group number.',
  'MA92': 'Missing/incomplete/invalid other payer\'s plan name.',
  'MA101': 'Missing/incomplete/invalid other payer\'s remittance advice.',
  'MA103': 'Missing/incomplete/invalid other payer\'s claim number.',
  'MA107': 'Missing/incomplete/invalid other payer\'s date of payment.',
  'MA108': 'Missing/incomplete/invalid other payer\'s total paid amount.',
  'MA109': 'Missing/incomplete/invalid other payer\'s allowed amount.',
  'MA110': 'Missing/incomplete/invalid other payer\'s deductible amount.',
  'MA111': 'Missing/incomplete/invalid other payer\'s coinsurance amount.',
  'MA112': 'Missing/incomplete/invalid other payer\'s copay amount.',
  'MA113': 'Missing/incomplete/invalid other payer\'s total adjustment amount.',
  'MA114': 'Missing/incomplete/invalid other payer\'s adjustment group code.',
  'MA115': 'Missing/incomplete/invalid other payer\'s adjustment reason code.',
  'MA120': 'Missing/incomplete/invalid other payer\'s remark code.',
  'MA121': 'Missing/incomplete/invalid other payer\'s patient responsibility amount.',
  'MA125': 'Missing/incomplete/invalid other payer\'s payment date.',
  'MA126': 'Missing/incomplete/invalid other payer\'s check/EFT number.',
  'MA128': 'Missing/incomplete/invalid other payer\'s check/EFT date.',
  'MA130': 'Missing/incomplete/invalid other payer\'s check/EFT amount.',
};

export function getCarcDescription(code: string): string {
  return CARC_DESCRIPTIONS[code] || 'Description not found for this code';
}

export function getRarcDescription(code: string): string {
  return RARC_DESCRIPTIONS[code] || 'Description not found for this code';
}
